<?php

namespace ContainerUFijApe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LSXSdySService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lSXSdyS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lSXSdyS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'exposition' => ['privates', '.errored..service_locator.lSXSdyS.App\\Entity\\Exposition', NULL, 'Cannot autowire service ".service_locator.lSXSdyS": it needs an instance of "App\\Entity\\Exposition" but this type has been excluded in "config/services.yaml".'],
        ], [
            'exposition' => 'App\\Entity\\Exposition',
        ]);
    }
}
