<?php

namespace ContainerUFijApe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExposition2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Mk89nnw.App\Entity\Exposition' shared service.
     *
     * @return \App\Entity\Exposition
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Mk89nnw": it needs an instance of "App\\Entity\\Exposition" but this type has been excluded in "config/services.yaml".');
    }
}
