<?php

namespace ContainerSvFouR6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P8CeVZAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P8CeVZA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P8CeVZA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'expositionRepository' => ['privates', 'App\\Repository\\ExpositionRepository', 'getExpositionRepositoryService', true],
        ], [
            'expositionRepository' => 'App\\Repository\\ExpositionRepository',
        ]);
    }
}
