<?php

namespace ContainerSvFouR6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mk89nnwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Mk89nnw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Mk89nnw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'exposition' => ['privates', '.errored..service_locator.Mk89nnw.App\\Entity\\Exposition', NULL, 'Cannot autowire service ".service_locator.Mk89nnw": it needs an instance of "App\\Entity\\Exposition" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'exposition' => 'App\\Entity\\Exposition',
        ]);
    }
}
