<?php

namespace ContainerSvFouR6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChaussure2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.q_cC_mb.App\Entity\Chaussure' shared service.
     *
     * @return \App\Entity\Chaussure
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.q_cC_mb": it needs an instance of "App\\Entity\\Chaussure" but this type has been excluded in "config/services.yaml".');
    }
}
