<?php

namespace ContainerSvFouR6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlacardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.K15.lNC.App\Entity\Placard' shared service.
     *
     * @return \App\Entity\Placard
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.K15.lNC": it needs an instance of "App\\Entity\\Placard" but this type has been excluded in "config/services.yaml".');
    }
}
