<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSvFouR6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSvFouR6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSvFouR6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSvFouR6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSvFouR6\App_KernelDevDebugContainer([
    'container.build_hash' => 'SvFouR6',
    'container.build_id' => '1e41f41f',
    'container.build_time' => 1699746333,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSvFouR6');
